mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('song.urls')),
    path('admin/', admin.site.urls),
]

song/urls.py
from django.urls import path
from . import views

app_name = 'song'
urlpatterns=[
    path('',views.index, name='index'),
    path('album/',views.album, name='album'),
    path('<int:album_id>/album/', views.album_id, name='album_info'),
    path('songs/', views.songs, name='songs'),
    path('<int:songs_id>/song/', views.song_id, name='song_info'),
    path('author/', views.author, name='author'),
    path('<int:author_id>/author/', views.author_id, name='author_id'),

]

song/models.py
from django.db import models

# Create your models here.
class Author(models.Model):

    name = models.CharField(max_length=40)
    age = models.CharField(max_length=3)
    photo = models.CharField(max_length=400)
    spotify_link = models.CharField(max_length=200)
    biography = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

class Song(models.Model):
    autor = models.ForeignKey(Author, on_delete=models.CASCADE)
    song_name = models.CharField(max_length=200)
    views = models.IntegerField(default=0)
    photo = models.CharField(max_length=400)
    spotify = models.CharField(max_length=400, null=True)
    lengths = models.CharField(max_length=40)
    lyrics = models.TextField(max_length=100000)


    def __str__(self):
        return self.song_name

class Album(models.Model):
    album_Name = models.CharField(max_length=40)
    autor = models.ForeignKey(Author, on_delete=models.CASCADE)
    songs = models.ManyToManyField(Song)
    views = models.IntegerField(default=0)
    photo = models.CharField(max_length=200)
    spotify_link = models.CharField(max_length=200)

    def __str__(self):
        return self.album_Name

song/views.py
from django.shortcuts import render
from django.http import HttpResponse,Http404
from .models import Author,Song,Album

# Create your views here.
def index(request):
    context = {'contenido': None}
    return render(request,'song/index.html',context)

def songs(request):
    list_of_songs = Song.objects.all()
    context = {'songs': list_of_songs}
    return render(request,'song/songs.html',context)

def author(request):
    list_of_authors = Author.objects.all()
    context = {'authors': list_of_authors,}
    return render(request,'song/author.html',context)

def album(request):
    list_of_albums = Album.objects.all()
    context = {'albums': list_of_albums}
    return render(request,'song/album.html',context)

def album_id(request,album_id):
    try:
        album_info = Album.objects.get(id=album_id)
        for song in album_info.songs.all():
            print(song)

        context = {'album': album_info}
        return render(request, 'song/single_album.html',context)
    except:
        raise Http404("Author not exist")

def author_id(request,author_id):
    try:
        author_info = Author.objects.get(id=author_id)
        context = {'author': author_info}
        return render(request, 'song/author_info.html',context)
    except:
        raise Http404("Author not exist")

def song_id(request,songs_id):
    try:
        song_info = Song.objects.get(id=songs_id)
        context = {'song': song_info}
        return render(request, 'song/song_info.html',context)
    except:
        raise Http404("Author not exist")

song/templates/song/album.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Album</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'song/album.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'song/images/music.png' %}">
</head>

<body>
        <header>
            <a href="{% url 'song:index' %}">
                <img class="logo" src="{% static 'song/images/logo_guillem.png' %}" alt="" draggable="false">
            </a>
        </header>

        <section>
            <img class="title_of_author" src="{% static 'song/images/album_titulo.png' %}" alt="" draggable="false">
        </section>
        <div class="wrapper">
        <div class="carousel">

            {% for album in albums%}
            <a class="image_link"href="{% url 'song:album_info' album.id %}"><img class="image_slider" src="{{album.photo}}" alt="" draggable="false"></a>
            {% endfor %}


        </div>

            <i id="left" class="fa-solid fa-angle-left">
                <img class="left_arrow_icon" src="{% static 'song/images/flecha-correcta.png' %}" alt="" draggable="false">

            </i>
            <i id="right" class="fa-solid fa-angle-right">
                <img class="right_arrow_icon" src="{% static 'song/images/flecha-correcta.png' %}" alt="" draggable="false">
            </i>

    </div>
</body>
    <script src="{% static 'song/slider.js' %}"></script>
</html>

song/templates/song/author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'song/author_page.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'song/images/music.png' %}">

</head>

<body>
        <header>
            <a href="{% url 'song:index' %}">
                <img class="logo" src="{% static 'song/images/logo_guillem.png' %}" alt="" draggable="false">
            </a>
        </header>

        <section>
            <img class="title_of_author" src="{% static 'song/images/artistas_logo.png' %}" alt="" draggable="false">
        </section>
        <div class="wrapper">
        <div class="carousel">

            {% for author in authors%}

            <a class="image_link"href="{% url 'song:author_id' author.id %}">
                <img class="image_slider" src="{{author.photo}}" alt="" draggable="false">
            </a>
            {% endfor %}


        </div>

            <i id="left" class="fa-solid fa-angle-left">
                <img class="left_arrow_icon" src="{% static 'song/images/flecha-correcta.png' %}" alt="" draggable="false">

            </i>
            <i id="right" class="fa-solid fa-angle-right">
                <img class="right_arrow_icon" src="{% static 'song/images/flecha-correcta.png' %}" alt="" draggable="false">
            </i>

    </div>
</body>
    <script src="{% static 'song/slider.js' %}"></script>
</html>

song/templates/song/author_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Single Author Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'song/single_author_page.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'song/images/music.png' %}">

</head>
<body>

    <header>
            <a href="{% url 'song:index' %}">
                <img class="logo" src="{% static 'song/images/logo_guillem.png' %}" alt="" draggable="false">
            </a>
        <img class="title_of_author" src="{% static 'song/images/artistas_logo.png' %}" alt="" draggable="false">

    </header>
    <section>
            <p>{{author.biography}}</p>
    </section>
    <img class="author_image" src="{{author.photo}}" alt="" draggable="false">

</body>
</html>

song/templates/song/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'song/images/music.png' %}">
    <link rel="stylesheet" href="{% static 'song/home.css' %}">
</head>
<body>
        <header>
            <a href="{% url 'song:index' %}">
                <img class="logo" src="{% static 'song/images/logo_guillem.png' %}" alt="" draggable="false">
            </a>
        </header>

        <section>
            <a class="link" href="{% url 'song:album' %}">
                <img class="album_label" src="{% static 'song/images/album_titulo.png' %}" alt="" draggable="false">
            </a>

            <a class="link" href="{% url 'song:songs' %}">
                <img class="cancion_label" src="{% static 'song/images/canciones_texto.png' %}" alt="" draggable="false">
            </a>

             <a class="link" href="{% url 'song:author' %}">
                <img class="artistas_label" src="{% static 'song/images/artistas_logo.png' %}" alt="" draggable="false">
             </a>
        </section>

         <img class="ilustracion_uno" src="{% static 'song/images/mac_miller.png' %}" alt="" draggable="false">
         <img class="ilustracion_dos" src="{% static 'song/images/cantante2.png' %}" alt="" draggable="false">


</body>
</html>

song/templates/song/single_album.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Songs</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'song/album-single.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'song/images/music.png' %}">

</head>

<body>
        <header>
            <a href="{% url 'song:index' %}">
                <img class="logo" src="{% static 'song/images/logo_guillem.png' %}" alt="" draggable="false">
            </a>
            <img class="title_of_author" src="{% static 'song/images/album_titulo.png' %}" alt="" draggable="false">
        </header>

        <section>
            <a href="{{album.spotify_link}}">
                <img src="{{album.photo}}">
                <h1>{{album.album_Name}}</h1>
            </a>
        </section>

        <div class="container_for_albums">

        {% for song in album.songs.all %}
        <div class="album">
            <a href="{{ song.spotify }}">
                <h1>{{ forloop.counter }}.{{ song }}</h1>
                <h1>{{ song.lengths }}</h1>
            </a>
        </div>
        {% endfor %}
        </div>
</body>
</html>

song/templates/song/song_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Song Info</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'song/song_info.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'song/images/music.png' %}">

</head>
<body>

    <header>
            <a href="{% url 'song:index' %}">
                <img class="logo" src="{% static 'song/images/logo_guillem.png' %}" alt="" draggable="false">
            </a>
        <img class="title_of_author" src="{% static 'song/images/letras_titulo.png' %}" alt="" draggable="false">
    </header>

    <div class="lyrics_div_content">
        <pre>{{song.lyrics}}</pre>
    </div>

    <section>
        <a class="spotiy_linkn "href="{{song.spotify}}">
        <img class="image_slider" src="{{song.photo}}" alt="" draggable="false"></a>
        <h1>{{song.song_name}}</h1>
        </a>
    </section>

</body>
</html>

song/templates/song/songs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Songs</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'song/songs.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'song/images/music.png' %}">


</head>

<body>
        <header>
            <a href="{% url 'song:index' %}">
                <img class="logo" src="{% static 'song/images/logo_guillem.png' %}" alt="" draggable="false">
            </a>
            <img class="title_of_author" src="{% static 'song/images/canciones_texto.png' %}" alt="" draggable="false">

        </header>

        <section>
                {% for song in songs %}
                <a class="image_link"href="{% url 'song:song_info' song.id %}"><img class="songs_images" src="{{song.photo}}" alt="" draggable="false"></a>
                <h1>{{song.song_name}}</h1>
                {% endfor %}
        </section>

</body>
</html>